/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;


import Controller.ClienteController;
import Models.Cliente;
import Utils.DateFormatterFactory;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class JPAtender extends javax.swing.JPanel {

    /**
     * Creates new form JPClientes
     */
    private FormState formState;

    public JPAtender() {
        initComponents();
        this.formState = FormState.SEARCH;
     
    }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBAtenderP = new javax.swing.JButton();
        jBAdFila = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fila de Atendimento");
        jPanel1.add(jLabel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, 20));

        jTFNome.setEditable(false);
        jTFNome.setToolTipText("");
        jPanel2.add(jTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 230, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Próximo cliente a ser atendido...");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 20));
        jLabel5.getAccessibleContext().setAccessibleName("Atender");

        jTFCodigo.setEditable(false);
        jTFCodigo.setToolTipText("");
        jPanel2.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 230, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Código:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 50, 20));

        jBAtenderP.setBackground(new java.awt.Color(0, 153, 255));
        jBAtenderP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jBAtenderP.setText("Atender o próximo");
        jBAtenderP.setBorder(null);
        jBAtenderP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtenderPActionPerformed(evt);
            }
        });
        jPanel2.add(jBAtenderP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 190, 70));

        jBAdFila.setBackground(new java.awt.Color(0, 153, 255));
        jBAdFila.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jBAdFila.setText("Adicionar Cliente");
        jBAdFila.setBorder(null);
        jBAdFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdFilaActionPerformed(evt);
            }
        });
        jPanel2.add(jBAdFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, 70));

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtenderPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtenderPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAtenderPActionPerformed

    private void jBAdFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdFilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdFila;
    private javax.swing.JButton jBAtenderP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
