/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;


import Controller.AtendenteController;
import Controller.ClienteController;
import Controller.ReservasController;
import Controller.PagamentoController;


import Models.Atendente;
import Models.Cliente;
import Models.Reserva;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class JPPagamento extends javax.swing.JPanel {

    /**
     * Creates new form JPClientes
     */
    private final ClienteController clienteController;
    private final ReservasController reservasController;
    private final AtendenteController atendenteController;
    private final PagamentoController pagamentoController;

    
    private FormState formState;

    public JPPagamento(){
        initComponents();
        this.reservasController = new ReservasController();
        this.clienteController = new ClienteController();
        this.atendenteController = new AtendenteController();
        this.pagamentoController = new PagamentoController();
        this.formState = FormState.SEARCH;
        addListenerSelectionTable();
    }
    
    public void refresh() {
        atualizarTabela1();
        atualizarTabela2();        
        updateButtons();
    }
    
    public void addListenerSelectionTable() {
        jTableReserva.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!jTableReserva.getSelectionModel().isSelectionEmpty()) {
                    updateEdits();
                }
            }
        });
    }
    
    public void updateButtons() {
        if (FormState.SEARCH == formState) {
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(false);
            jBGravar.setEnabled(false);
        } else if (FormState.INSERT == formState) {
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);
        } else if (FormState.EDIT == formState) {
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);            
        }
    }
    
     public void updateEdits() {        
        jTFCodigo.setText("");
        jTFNome.setText("");        
        jTFQuarto.setText("");
        //JCPago
        Object cliente = jTableReserva.getValueAt(jTableReserva.getSelectedRow(), 1);
        Object quarto = jTableReserva.getValueAt(jTableReserva.getSelectedRow(), 2);
        Object pago = jTableReserva.getValueAt(jTableReserva.getSelectedRow(), 3);        
        //
        jTFCodigo.setText(jTableReserva.getValueAt(jTableReserva.getSelectedRow(), 0).toString());
        if (cliente != null) {
            jTFNome.setText(cliente.toString());            
        }
        if (quarto != null) {
            jTFQuarto.setText(quarto.toString());
        }
        if (pago != null) {
            if (pago.equals(true)){
                JCPago.setSelectedItem("Sim");
            } else {
                JCPago.setSelectedItem("Não");
            }
            //JCPago.setSelectedItem(pago);
        }                        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReserva = new javax.swing.JTable();
        jBGravar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFQuarto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReserva2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        JCPago = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pagamentos");
        jPanel1.add(jLabel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserva", "Nome", "Quarto", "Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReserva.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableReserva.setShowGrid(false);
        jTableReserva.getTableHeader().setReorderingAllowed(false);
        jTableReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableReserva);
        if (jTableReserva.getColumnModel().getColumnCount() > 0) {
            jTableReserva.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableReserva.getColumnModel().getColumn(2).setMaxWidth(50);
            jTableReserva.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 250, 150));

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pago:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jTFQuarto.setEditable(false);
        jTFQuarto.setToolTipText("");
        jTFQuarto.setEnabled(false);
        jPanel2.add(jTFQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        jTFNome.setEditable(false);
        jTFNome.setToolTipText("");
        jTFNome.setEnabled(false);
        jPanel2.add(jTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 230, 30));

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Reserva:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jTFCodigo.setEditable(false);
        jTFCodigo.setToolTipText("");
        jTFCodigo.setEnabled(false);
        jPanel2.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 230, 30));

        jBCancelar.setText("Cancelar");
        jBCancelar.setActionCommand("");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quarto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Pendências");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jTableReserva2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserva", "Nome", "CPF", "Atendente", "Quarto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReserva2.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableReserva2.setShowGrid(false);
        jTableReserva2.getTableHeader().setReorderingAllowed(false);
        jTableReserva2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReserva2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableReserva2);
        if (jTableReserva2.getColumnModel().getColumnCount() > 0) {
            jTableReserva2.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableReserva2.getColumnModel().getColumn(1).setMinWidth(100);
            jTableReserva2.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableReserva2.getColumnModel().getColumn(3).setMinWidth(100);
            jTableReserva2.getColumnModel().getColumn(4).setMaxWidth(50);
            jTableReserva2.getColumnModel().getColumn(5).setMaxWidth(70);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 570, 150));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Histórico");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        JCPago.setEditable(true);
        JCPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        JCPago.setToolTipText("");
        jPanel2.add(JCPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 110, 30));

        add(jPanel2, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        
        if (formState == FormState.EDIT) {
           jTFCodigo.setEnabled(true);
           jTFQuarto.setEnabled(true);
           jTFNome.setEnabled(true);
        
        // Obtendo o valor do JComboBox e averiguando se é uma afirmação
        boolean isPaid = JCPago.getSelectedItem().equals("Sim");
        
        // Verifica se o valor selecionado é "true" para marcar a reserva como paga
        if (isPaid) {
            pagamentoController.marcarReservaComoPaga(Integer.valueOf(jTFCodigo.getText()));
            jTFCodigo.setText("");
            jTFNome.setText("");        
            jTFQuarto.setText("");
        }
        //
        }
       
        //
        atualizarTabela1();
        atualizarTabela2();
        //
        formState = FormState.SEARCH;
        updateButtons();
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        updateEdits();
        formState = FormState.EDIT;
        updateButtons();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed

    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        formState = FormState.SEARCH;
        updateButtons();       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTableReserva2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReserva2MouseClicked
    }//GEN-LAST:event_jTableReserva2MouseClicked

    private void jTableReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReservaMouseClicked
        jBEditar.setEnabled(true);
    }//GEN-LAST:event_jTableReservaMouseClicked

   private void atualizarTabela1() {
        DefaultTableModel model = (DefaultTableModel) jTableReserva.getModel();
        model.setRowCount(0);
        ArrayList<Reserva> lista = reservasController.verPendencias();
        for (Reserva r : lista) {
            Cliente c = clienteController.acessarCliente(r.getIdCliente());
            Object[] dados = {r.getNum(), 
                                c.getNome(),
                                r.getIdQuarto(),
                                r.estaPago()};
            model.addRow(dados);
        }
    }
   
    private void atualizarTabela2() {
        DefaultTableModel model = (DefaultTableModel) jTableReserva2.getModel();
        model.setRowCount(0);
        ArrayList<Reserva> lista = reservasController.acessarReservas();
        for (Reserva r : lista) {
            Cliente c = clienteController.acessarCliente(r.getIdCliente());
            Atendente a = atendenteController.acessarAtendente(r.getIdAtendente());            
            Object[] dados = {r.getNum(), 
                                c.getNome(),
                                c.getCpf(),
                                a.getNome(),
                                r.getIdQuarto(),
                                "R$ " + String.format("%.2f", r.getValorPagamento())
            };
            model.addRow(dados);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCPago;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFQuarto;
    private javax.swing.JTable jTableReserva;
    private javax.swing.JTable jTableReserva2;
    // End of variables declaration//GEN-END:variables
}