/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;


import Controller.ClienteController;
import Models.Cliente;
import Utils.DateFormatterFactory;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class JPPagamento extends javax.swing.JPanel {

    /**
     * Creates new form JPClientes
     */
    private final ClienteController clienteController;
    private FormState formState;

    public JPPagamento() {
        initComponents();
        this.clienteController = new ClienteController();
        this.formState = FormState.SEARCH;
        //
        atualizarTabela();        
        updateButtons();
        //
        addListenerSelectionTable();
    }
    
    public void addListenerSelectionTable() {
        jTableCliente.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!jTableCliente.getSelectionModel().isSelectionEmpty()) {
                    updateEdits();
                }
            }
        });
    }
    
    public void updateButtons() {
        if (FormState.SEARCH == formState) {
            jBEditar.setEnabled(true);
            jBCancelar.setEnabled(false);
            jBGravar.setEnabled(false); 
        } else if (FormState.INSERT == formState) {
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);
        } else if (FormState.EDIT == formState) {
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);            
        }
    }
    
    public void updateEdits() {        
        jTFNome.setText("");
        jTFQuarto.setText("");
        jTFQuarto.setText("");
        //        
        Object nome = jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 1);
        Object telefone = jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 2);
        Object cpf = jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 3);
        Object dataNasc = jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 4);        
        //
        jTFCodigo.setText(jTableCliente.getValueAt(jTableCliente.getSelectedRow(), 0).toString());
        if (nome != null) {
            jTFNome.setText(nome.toString());
        }
        if (telefone != null) {
            jTFQuarto.setText(telefone.toString());
        }
        if (dataNasc != null) {            
            jTFQuarto.setText(jTFQuarto.toString());       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jBGravar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFQuarto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFTelefone1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCliente1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tela Pagamentos");
        jPanel1.add(jLabel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quarto", "Pago"
            }
        ));
        jTableCliente.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableCliente.setShowGrid(false);
        jScrollPane1.setViewportView(jTableCliente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 240, 150));

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pago:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jTFQuarto.setEditable(false);
        jTFQuarto.setToolTipText("");
        jPanel2.add(jTFQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 230, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        jTFNome.setEditable(false);
        jTFNome.setToolTipText("");
        jPanel2.add(jTFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 230, 30));

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Código:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jTFCodigo.setEditable(false);
        jTFCodigo.setToolTipText("");
        jPanel2.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 230, 30));

        jBCancelar.setText("Cancelar");
        jBCancelar.setActionCommand("");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quarto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pendências");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jTFTelefone1.setToolTipText("");
        jPanel2.add(jTFTelefone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 30));

        jTableCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Atendente", "Quarto", "Valor"
            }
        ));
        jTableCliente1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableCliente1.setShowGrid(false);
        jScrollPane2.setViewportView(jTableCliente1);
        if (jTableCliente1.getColumnModel().getColumnCount() > 0) {
            jTableCliente1.getColumnModel().getColumn(2).setHeaderValue("CPF");
            jTableCliente1.getColumnModel().getColumn(3).setHeaderValue("Atendente");
            jTableCliente1.getColumnModel().getColumn(5).setHeaderValue("Valor");
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 570, 150));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Historico");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        add(jPanel2, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        DateFormat df = DateFormatterFactory.dateFormatddMMyyy();
   
        try {              
            if (formState == FormState.INSERT) {  
                clienteController.inserirCliente(new Cliente(0,
                        jTFNome.getText(),
                        jTFQuarto.getText(),
                        df.parse(jTFQuarto.getText())));
            
            } else if (formState == FormState.EDIT) {
                clienteController.editarCliente(new Cliente(Integer.valueOf(jTFCodigo.getText()), 
                                                        jTFNome.getText(), 
                                                        jTFQuarto.getText(), 
                                                        df.parse(jTFQuarto.getText())));
            }        
        } catch (ParseException ex) {
                Logger.getLogger(JPPagamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        //
        atualizarTabela();
        //
        formState = FormState.SEARCH;
        updateButtons();
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:    
        updateEdits();
        //
        formState = FormState.EDIT;
        //
        updateButtons();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        jTFCodigo.setText("");
        jTFNome.setText("");
        jTFQuarto.setText("");
        jTFQuarto.setText("");
        //
        formState = FormState.INSERT;
        //
        updateButtons();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
       
        formState = FormState.SEARCH;
        //
        updateButtons();       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) jTableCliente.getModel();
        model.setRowCount(0);
        ArrayList<Cliente> lista = clienteController.consultarCliente();
        
                
        DateFormat df = DateFormatterFactory.dateFormatddMMyyy();
        

        for (Cliente c : lista) {
            Object[] dados = {c.getId(), c.getNome(), c.getCpf(), c.getTelefone(), df.format(c.getDataNasc())};
            model.addRow(dados);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFQuarto;
    private javax.swing.JTextField jTFTelefone1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableCliente1;
    // End of variables declaration//GEN-END:variables
}
