/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Controller.QuartosController;
import Models.Quarto;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class JPQuarto extends javax.swing.JPanel {

    /**
     * Creates new form JPClientes
     */
    private final QuartosController quartoController;
    private FormState formState;

    public JPQuarto() {
        initComponents();
        this.quartoController = new QuartosController();
        this.formState = FormState.SEARCH;        
        //
        addListenerSelectionTable();
    }
    
    public void refresh() {
        atualizarTabela();
        updateButtons();
    }
    
    private void addListenerSelectionTable() {
        jTableQuarto.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!jTableQuarto.getSelectionModel().isSelectionEmpty()) {
                    updateEdits();
                }
            }
        });
    }
    
    private void updateButtons() {
        if (FormState.SEARCH == formState) {
            jBNovo.setEnabled(true);
            jBEditar.setEnabled(true);
            jBCancelar.setEnabled(false);
            jBGravar.setEnabled(false); 
        } else if (FormState.INSERT == formState) {
            jBNovo.setEnabled(false);
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);
        } else if (FormState.EDIT == formState) {
            jBNovo.setEnabled(false);
            jBEditar.setEnabled(false);
            jBCancelar.setEnabled(true);
            jBGravar.setEnabled(true);            
        }
    }
    
    public void updateEdits() {        
        jTFCodigo.setText("");
        jTFNumQuarto.setText("");
        /*
        jCReservado.setText("");
        jCReservado.setText("");
        */
        //        
        Object numQuarto = jTableQuarto.getValueAt(jTableQuarto.getSelectedRow(), 1);
        Object tamanho = jTableQuarto.getValueAt(jTableQuarto.getSelectedRow(), 2);
        Object reservado = jTableQuarto.getValueAt(jTableQuarto.getSelectedRow(), 3);       
        //
        jTFCodigo.setText(jTableQuarto.getValueAt(jTableQuarto.getSelectedRow(), 0).toString());
        if (numQuarto != null) {
            jTFNumQuarto.setText(numQuarto.toString());
        }
        if (tamanho != null) {            
            if (tamanho.toString().equals("P")) {
                jCTamanho.setSelectedIndex(0);
            } else if (tamanho.toString().equals("M")) {
                jCTamanho.setSelectedIndex(1);
            } else if (tamanho.toString().equals("G")) {
                jCTamanho.setSelectedIndex(2);
            }                                             
        }
        if (reservado != null) {
            if ((boolean) reservado)  {
                jCReservado.setSelectedIndex(0);
            } else {
                jCReservado.setSelectedIndex(1);
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQuarto = new javax.swing.JTable();
        jBGravar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNumQuarto = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jCReservado = new javax.swing.JComboBox<>();
        jCTamanho = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quartos");
        jPanel1.add(jLabel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Número do Quarto", "Tamanho", "Reservado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableQuarto.setMinimumSize(new java.awt.Dimension(0, 0));
        jTableQuarto.setShowGrid(false);
        jTableQuarto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableQuarto);
        if (jTableQuarto.getColumnModel().getColumnCount() > 0) {
            jTableQuarto.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableQuarto.getColumnModel().getColumn(3).setMaxWidth(160);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 570, 240));

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jPanel2.add(jBGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Reservado:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tamanho:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Número:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        jTFNumQuarto.setToolTipText("");
        jPanel2.add(jTFNumQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, 30));

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, -1));

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });
        jPanel2.add(jBNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));

        jTFCodigo.setEditable(false);
        jTFCodigo.setToolTipText("");
        jPanel2.add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 30));

        jBCancelar.setText("Cancelar");
        jBCancelar.setActionCommand("");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, -1));

        jCReservado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));
        jCReservado.setToolTipText("");
        jCReservado.setEnabled(false);
        jPanel2.add(jCReservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 60, 30));

        jCTamanho.setEditable(true);
        jCTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "M", "G" }));
        jCTamanho.setToolTipText("");
        jCTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTamanhoActionPerformed(evt);
            }
        });
        jPanel2.add(jCTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 60, 30));

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        if (formState == FormState.INSERT) {
            quartoController.inserirQuarto(new Quarto(
                    Integer.valueOf(jTFNumQuarto.getText()),
                    jCTamanho.getItemAt(jCTamanho.getSelectedIndex()).toCharArray()[0]));
            
        } else if (formState == FormState.EDIT) {
            quartoController.editarQuarto(new Quarto(
                    Integer.valueOf(jTFCodigo.getText()),
                    Integer.valueOf(jTFNumQuarto.getText()),
                    jCTamanho.getItemAt(jCTamanho.getSelectedIndex()).toCharArray()[0]));
        }
        //
        atualizarTabela();
        //
        formState = FormState.SEARCH;
        updateButtons();
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:    
        updateEdits();
        //
        formState = FormState.EDIT;
        //
        updateButtons();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        jTFCodigo.setText("");
        jTFNumQuarto.setText("");        
        //
        formState = FormState.INSERT;
        //
        updateButtons();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:       
        formState = FormState.SEARCH;
        //
        updateButtons();       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTamanhoActionPerformed

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) jTableQuarto.getModel();
        model.setRowCount(0);
        ArrayList<Quarto> lista = quartoController.conultarQuartos();

        for (Quarto q : lista) {
            Object[] dados = {q.getId(), q.getNum(), q.getTamanho(), q.isReservado()};
            model.addRow(dados);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBNovo;
    private javax.swing.JComboBox<String> jCReservado;
    private javax.swing.JComboBox<String> jCTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNumQuarto;
    private javax.swing.JTable jTableQuarto;
    // End of variables declaration//GEN-END:variables
}

